# Generated by Django 5.1.4 on 2026-08-16 16:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDefaultPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))])),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_percent', to='catalog.evecategory')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))])),
                ('categories', models.ManyToManyField(blank=True, to='catalog.evecategory')),
                ('groups', models.ManyToManyField(blank=True, to='catalog.evegroup')),
                ('types', models.ManyToManyField(blank=True, to='catalog.evetype')),
            ],
            options={
                'ordering': ['label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, to='catalog.evecategory')),
                ('groups', models.ManyToManyField(blank=True, to='catalog.evegroup')),
                ('types', models.ManyToManyField(blank=True, to='catalog.evetype')),
            ],
            options={
                'ordering': ['-valid_from'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.evecategory')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.evegroup')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.evetype')),
            ],
            options={
                'verbose_name_plural': 'blacklist entries',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('group__isnull', True), ('type__isnull', True)), models.Q(('category__isnull', True), ('group__isnull', False), ('type__isnull', True)), models.Q(('category__isnull', True), ('group__isnull', True), ('type__isnull', False)), _connector='OR'), name='blacklist_entry_exactly_one_target')],
            },
        ),
    ]
