# Generated by Django 5.1.4 on 2026-08-17 15:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_evetype_portion_size_evetypematerial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReprocessingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('yield_rate', models.DecimalField(decimal_places=4, help_text='Recovery fraction, e.g. 0.9063 for 90.63%. Ore and ice use different reprocessing skills, so they usually need separate rules.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('categories', models.ManyToManyField(blank=True, to='catalog.evecategory')),
                ('groups', models.ManyToManyField(blank=True, to='catalog.evegroup')),
                ('types', models.ManyToManyField(blank=True, to='catalog.evetype')),
            ],
            options={
                'ordering': ['label'],
                'abstract': False,
            },
        ),
    ]
