# Generated by Django 5.1.4 on 2026-08-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contract_to', models.CharField(blank=True, max_length=255)),
                ('contract_instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('type_name', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_applied', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_source_kind', models.CharField(help_text='Machine key for which category of rule won. Translated at render.', max_length=32)),
                ('price_source_label', models.CharField(blank=True, default='', help_text='Admin-authored rule name. Never translated — it is data, not UI.', max_length=120)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason_code', models.CharField(blank=True, help_text='Machine key for why the line was rejected. Translated at render.', max_length=32, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buyback.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
