# Generated by Django 5.1.4 on 2026-08-16 13:27
# Hand-edited: the auto-generated RemoveField operations for the legacy
# price_source/flag_reason columns were split out into
# 0004_drop_legacy_label_columns.py, which runs after the 0003 backfill.
# Removing the legacy columns here would delete the data the backfill needs
# to read.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='flag_reason_code',
            field=models.CharField(blank=True, help_text='Machine key for why the line was rejected. Translated at render.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='price_source_kind',
            field=models.CharField(default='', help_text='Machine key for which category of rule won. Translated at render.', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='price_source_label',
            field=models.CharField(blank=True, default='', help_text='Admin-authored rule name. Never translated — it is data, not UI.', max_length=120),
        ),
    ]
