# Generated by Django 5.1.4 on 2026-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='contract_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quote',
            name='contract_station',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
