# Generated by Django 5.1.4 on 2026-08-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback', '0002_freeze_contract_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='portion_size_applied',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='yield_rate_applied',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='QuoteItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField()),
                ('type_name', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_applied', models.DecimalField(decimal_places=2, max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_unpriced', models.BooleanField(default=False)),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='buyback.quoteitem')),
            ],
            options={
                'ordering': ['-line_total', 'type_name'],
            },
        ),
    ]
