# Generated by Django 5.1.4 on 2026-08-17 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsiCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField()),
                ('character_name', models.CharField(max_length=255)),
                ('refresh_token_ciphertext', models.TextField(blank=True, help_text='Fernet ciphertext. Cleared on disconnect; never stored in plain text.')),
                ('scopes', models.TextField(blank=True, help_text='Space-separated, as SSO returns them.')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'ESI character',
                'verbose_name_plural': 'ESI character',
            },
        ),
    ]
