# Generated by Django 5.1.4 on 2026-08-17 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetype',
            name='portion_size',
            field=models.PositiveIntegerField(default=1, help_text='Units consumed per reprocessing batch. 100 for raw ore, 1 for ice.'),
        ),
        migrations.CreateModel(
            name='EveTypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocesses_from', to='catalog.evetype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.evetype')),
            ],
            options={
                'ordering': ['type_id', 'material_id'],
                'constraints': [models.UniqueConstraint(fields=('type', 'material'), name='eve_type_material_unique')],
            },
        ),
    ]
