# Generated by Django 5.1.4 on 2026-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.PositiveIntegerField(default=2, help_text='Janice market ID. 2 = Jita.')),
                ('pricing_basis', models.CharField(choices=[('buy', 'Buy price'), ('split', 'Split price'), ('sell', 'Sell price')], default='split', max_length=16)),
                ('pricing_variant', models.CharField(choices=[('immediate', 'Immediate'), ('top5percent', 'Top 5 percent')], default='immediate', max_length=16)),
                ('contract_to', models.CharField(blank=True, help_text='Character or corporation that sellers should contract to.', max_length=255)),
                ('contract_instructions', models.TextField(blank=True, help_text='Shown on every quote and frozen into each snapshot.')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
