# Generated by Django 5.1.4 on 2026-08-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_description',
            field=models.TextField(blank=True, help_text='Shown on the home page.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_footer',
            field=models.TextField(blank=True, help_text='Shown at the bottom of every page.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Shown on every page.', upload_to='siteconfig/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(blank=True, help_text='Website name for the buyback.', max_length=255),
        ),
    ]
