# Generated by Django 5.1.4 on 2026-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_siteconfig_site_description_siteconfig_site_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Shown on every page.', upload_to='static/img/'),
        ),
    ]
