# Generated by Django 5.1.4 on 2026-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_alter_siteconfig_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contract_default_days',
            field=models.PositiveIntegerField(default=3, help_text='Default number of days for the contract.'),
        ),
    ]
