# Generated by Django 5.1.4 on 2026-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_siteconfig_contract_default_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contract_station',
            field=models.CharField(blank=True, help_text='Station where the contract should be delivered (frozen into each quote).', max_length=255),
        ),
    ]
