# Generated by Django 5.1.4 on 2026-08-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_siteconfig_contract_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Shown on every page.', upload_to=''),
        ),
    ]
