# Generated by Django 5.1.4 on 2026-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_logo_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Shown in the header on every page. Resized to fit 512px on save, so a small file is fine — the original is not kept.', upload_to='logos/'),
        ),
    ]
