# Generated by Django 5.1.4 on 2026-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_alter_siteconfig_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, height_field='logo_height', help_text='Shown in the header on every page. Resized to fit 512px on save, so a small file is fine — the original is not kept.', upload_to='logos/', width_field='logo_width'),
        ),
    ]
