# Generated by Django 5.1.4 on 2026-08-18 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0009_alter_siteconfig_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_display_height',
            field=models.PositiveIntegerField(default=40, help_text="Height of the logo in the site header, in pixels. Width follows the image's own proportions.", validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo_display_max_width',
            field=models.PositiveIntegerField(default=160, help_text='Widest the logo may render, in pixels. Stops a very wide logo squeezing the site name out of the header.', validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(800)]),
        ),
    ]
